language: java

jobs:
  include:
  - os: linux
    arch: amd64
  - os: osx

script:
 - ./gradlew build --console=plain --no-daemon

after_failure:
 - cat MinieLibrary/build/reports/tests/test/classes/jme3utilities.minie.test.TestDefaults.html