---
# configure deployment and continuous integration at travis-ci.com

dist: bionic
language: java

jobs:
  include:
    - os: linux
      arch: arm64
      addons:
        apt:
          packages:
            - default-jre
          update: true

script:
  - ./gradlew build --console=plain --no-daemon

after_failure:
  - cat MinieLibrary/build/reports/tests/test/classes/jme3utilities.minie.test.TestDefaults.html
