language: java

matrix:
  include:
  - os: linux
  - os: osx

script:
 - ./gradlew build --console=plain --no-daemon

after_failure:
 - cat MinieLibrary/build/reports/tests/test/classes/jme3utilities.minie.test.TestDefaults.html