site:
  title: The Minie project
  start_page: minie:ROOT:overview.adoc
  url: https://stephengold.github.io/Minie
content:
  sources:
  - url: https://github.com/stephengold/Minie.git
    branches: master
    start_path: src/site/antora/minie-project
  - url: https://github.com/stephengold/Minie.git
    branches: master
    start_path: MinieLibrary/src/site/antora/tutorials
ui:
  bundle:
    url: https://github.com/stephengold/antora-ui-bundle/releases/download/v-sgold200617a/ui-bundle.zip
    snapshot: true
