---
# configure Antora for local testing with a local bundle

site:
  title: The Minie project (local test using a local bundle)
  start_page: minie:ROOT:overview.adoc
  url: /home/sgold/NetBeansProjects/Minie/build/site
content:
  sources:
    - url: /home/sgold/NetBeansProjects/Minie
      branches: master
      start_path: src/site/antora/minie-project
    - url: /home/sgold/NetBeansProjects/Minie
      branches: master
      start_path: MinieLibrary/src/site/antora/tutorials
ui:
  bundle:
    url: /home/sgold/NetBeansProjects/antora-ui-bundle/build/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: build/site
