name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Open an issue ONLY if you''ve found a reproducible defect in the software or its documentation. If you need help, use the JMonkeyEngine Forum.'
