---
# GitHub workflow for commits pushed to the Minie repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java8-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java8-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java8-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug -Ppdb64 --console=plain --no-daemon --stacktrace
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java11-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: 'build/reports/tests/test/index.html'

  Java11-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug -Ppdb64 --console=plain --no-daemon --stacktrace
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java16-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java16-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java16-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug -Ppdb64 --console=plain --no-daemon --stacktrace
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'