---
# GitHub workflow for commits pushed to the Minie repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java8-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'
